version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: python:3.7-alpine3.11
      
  
    working_directory: ~/repo
    
    steps:
      - checkout
      
    #Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ "requirements.txt" }}        
            #fallback to using the latest cache if no exact match is fpound
            - v1-dependencies-

      - run:         
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install make
            make install
            
      
      - save_cache:
          paths:
            - ./venv
          key: vi-dependencies-{{ checksum "requirements.txt" }}
      
      - run:
          name: run lint
          command: |
           . venv/bin/activate
           make lint
           

workflows:
  main:
    jobs:
      - build
